-- 1. Create all core tables (if missing)
-- This ensures the script doesn't fail when altering non-existent tables.
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    buy_price NUMERIC DEFAULT 0,
    sell_price NUMERIC DEFAULT 0,
    quantity INTEGER DEFAULT 0,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id),
    quantity INTEGER NOT NULL,
    buy_price NUMERIC,
    sell_price NUMERIC,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    commission_fee NUMERIC DEFAULT 0,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manual_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. Ensure user_id column exists on all tables (Backfill for existing tables)
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='products') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='user_id') THEN
            ALTER TABLE products ADD COLUMN user_id UUID REFERENCES auth.users(id);
        END IF;
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='sales') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='sales' AND column_name='user_id') THEN
            ALTER TABLE sales ADD COLUMN user_id UUID REFERENCES auth.users(id);
        END IF;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='payments') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='user_id') THEN
            ALTER TABLE payments ADD COLUMN user_id UUID REFERENCES auth.users(id);
        END IF;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='expenses') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='expenses' AND column_name='user_id') THEN
            ALTER TABLE expenses ADD COLUMN user_id UUID REFERENCES auth.users(id);
        END IF;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='manual_reports') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='manual_reports' AND column_name='user_id') THEN
            ALTER TABLE manual_reports ADD COLUMN user_id UUID REFERENCES auth.users(id);
        END IF;
    END IF;
END $$;

-- 2. Ensure shipments table has all required columns
-- This fixes the "create shipment is not working" issue.
DO $$ 
BEGIN
    -- Create shipments table if it doesn't exist
    CREATE TABLE IF NOT EXISTS shipments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
        status TEXT DEFAULT 'pending' NOT NULL,
        user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
    );

    -- Create shipment_items table if it doesn't exist
    CREATE TABLE IF NOT EXISTS shipment_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        shipment_id BIGINT REFERENCES shipments(id) ON DELETE CASCADE,
        product_id BIGINT REFERENCES products(id),
        quantity INTEGER NOT NULL
    );

    -- Add columns if they are missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='supplier_name') THEN
        ALTER TABLE shipments ADD COLUMN supplier_name TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='total_cost') THEN
        ALTER TABLE shipments ADD COLUMN total_cost NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='shipping_cost') THEN
        ALTER TABLE shipments ADD COLUMN shipping_cost NUMERIC DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='description') THEN
        ALTER TABLE shipments ADD COLUMN description TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='weight_kg') THEN
        ALTER TABLE shipments ADD COLUMN weight_kg NUMERIC;
    END IF;
END $$;

-- 3. Enable RLS on all tables
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- 4. Create Customers table (if not exists)
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 5. Create policies for User Profiles
DROP POLICY IF EXISTS "Users can select their own profile" ON user_profiles;
CREATE POLICY "Users can select their own profile" ON user_profiles
    FOR SELECT TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON user_profiles;
CREATE POLICY "Users can insert their own profile" ON user_profiles
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON user_profiles;
CREATE POLICY "Users can update their own profile" ON user_profiles
    FOR UPDATE TO authenticated USING (auth.uid() = id);

-- 6. Create policies for Products
DROP POLICY IF EXISTS "Users can manage their own products" ON products;
CREATE POLICY "Users can manage their own products" ON products
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 7. Create policies for Shipments
DROP POLICY IF EXISTS "Users can manage their own shipments" ON shipments;
CREATE POLICY "Users can manage their own shipments" ON shipments
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 8. Create policies for Shipment Items
DROP POLICY IF EXISTS "Users can manage their own shipment items" ON shipment_items;
CREATE POLICY "Users can manage their own shipment items" ON shipment_items
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM shipments 
            WHERE shipments.id = shipment_items.shipment_id 
            AND shipments.user_id = auth.uid()
        )
    );

-- 9. Create policies for Sales
DROP POLICY IF EXISTS "Users can manage their own sales" ON sales;
CREATE POLICY "Users can manage their own sales" ON sales
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 10. Create policies for Payments
DROP POLICY IF EXISTS "Users can manage their own payments" ON payments;
CREATE POLICY "Users can manage their own payments" ON payments
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 11. Create policies for Expenses
DROP POLICY IF EXISTS "Users can manage their own expenses" ON expenses;
CREATE POLICY "Users can manage their own expenses" ON expenses
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 12. Create policies for Manual Reports
DROP POLICY IF EXISTS "Users can manage their own reports" ON manual_reports;
CREATE POLICY "Users can manage their own reports" ON manual_reports
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 13. Create policies for Customers
DROP POLICY IF EXISTS "Users can manage their own customers" ON customers;
CREATE POLICY "Users can manage their own customers" ON customers
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 14. Force PostgREST to reload the schema cache
NOTIFY pgrst, 'reload schema';
