-- 1. Create all core tables (if missing)
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    buy_price NUMERIC DEFAULT 0,
    sell_price NUMERIC DEFAULT 0,
    quantity INTEGER DEFAULT 0,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    image_url TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL,
    buy_price NUMERIC,
    sell_price NUMERIC,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    commission_fee NUMERIC DEFAULT 0,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    description TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS manual_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name TEXT,
    total_cost NUMERIC DEFAULT 0,
    shipping_cost NUMERIC DEFAULT 0,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL,
    description TEXT,
    weight_kg NUMERIC,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shipment_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT REFERENCES shipments(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    address TEXT,
    notes TEXT,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. Ensure all tables have NOT NULL user_id and proper constraints
-- This handles existing tables from previous versions.
DO $$ 
BEGIN
    -- Products
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='user_id') THEN
        DELETE FROM products WHERE user_id IS NULL;
        ALTER TABLE products ALTER COLUMN user_id SET NOT NULL;
    END IF;
    
    -- Sales
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='sales' AND column_name='user_id') THEN
        DELETE FROM sales WHERE user_id IS NULL;
        ALTER TABLE sales ALTER COLUMN user_id SET NOT NULL;
    END IF;

    -- Payments
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='user_id') THEN
        DELETE FROM payments WHERE user_id IS NULL;
        ALTER TABLE payments ALTER COLUMN user_id SET NOT NULL;
    END IF;

    -- Expenses
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='expenses' AND column_name='user_id') THEN
        DELETE FROM expenses WHERE user_id IS NULL;
        ALTER TABLE expenses ALTER COLUMN user_id SET NOT NULL;
    END IF;

    -- Shipments
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='shipments' AND column_name='user_id') THEN
        DELETE FROM shipments WHERE user_id IS NULL;
        ALTER TABLE shipments ALTER COLUMN user_id SET NOT NULL;
    END IF;

    -- Customers
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='customers' AND column_name='user_id') THEN
        DELETE FROM customers WHERE user_id IS NULL;
        ALTER TABLE customers ALTER COLUMN user_id SET NOT NULL;
    END IF;
END $$;

-- 3. Enable RLS on all tables
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE manual_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 5. Create policies for User Profiles
DROP POLICY IF EXISTS "Users can select their own profile" ON user_profiles;
CREATE POLICY "Users can select their own profile" ON user_profiles
    FOR SELECT TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON user_profiles;
CREATE POLICY "Users can insert their own profile" ON user_profiles
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON user_profiles;
CREATE POLICY "Users can update their own profile" ON user_profiles
    FOR UPDATE TO authenticated USING (auth.uid() = id);

-- 6. Create policies for Products
DROP POLICY IF EXISTS "Users can manage their own products" ON products;
CREATE POLICY "Users can manage their own products" ON products
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 7. Create policies for Shipments
DROP POLICY IF EXISTS "Users can manage their own shipments" ON shipments;
CREATE POLICY "Users can manage their own shipments" ON shipments
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 8. Create policies for Shipment Items
DROP POLICY IF EXISTS "Users can manage their own shipment items" ON shipment_items;
CREATE POLICY "Users can manage their own shipment items" ON shipment_items
    FOR ALL TO authenticated USING (
        EXISTS (
            SELECT 1 FROM shipments 
            WHERE shipments.id = shipment_items.shipment_id 
            AND shipments.user_id = auth.uid()
        )
    );

-- 9. Create policies for Sales
DROP POLICY IF EXISTS "Users can manage their own sales" ON sales;
CREATE POLICY "Users can manage their own sales" ON sales
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 10. Create policies for Payments
DROP POLICY IF EXISTS "Users can manage their own payments" ON payments;
CREATE POLICY "Users can manage their own payments" ON payments
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 11. Create policies for Expenses
DROP POLICY IF EXISTS "Users can manage their own expenses" ON expenses;
CREATE POLICY "Users can manage their own expenses" ON expenses
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 12. Create policies for Manual Reports
DROP POLICY IF EXISTS "Users can manage their own reports" ON manual_reports;
CREATE POLICY "Users can manage their own reports" ON manual_reports
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 13. Create policies for Customers
DROP POLICY IF EXISTS "Users can manage their own customers" ON customers;
CREATE POLICY "Users can manage their own customers" ON customers
    FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 14. Force PostgREST to reload the schema cache
NOTIFY pgrst, 'reload schema';
