import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Sale } from '../domain/models';

export class PDFService {
    static async generateInvoice(sale: Sale, storeSettings: any) {
        const html = `
            <html>
                <head>
                    <style>
                        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
                        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #7C3AED; padding-bottom: 20px; }
                        .store-name { font-size: 28px; font-weight: bold; color: #7C3AED; }
                        .invoice-title { font-size: 20px; margin-top: 10px; color: #666; }
                        .details { margin-bottom: 40px; }
                        .row { display: flex; justify-content: space-between; margin-bottom: 10px; }
                        .label { font-weight: bold; color: #666; }
                        .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                        .table th { background: #7C3AED; color: white; padding: 12px; text-align: left; }
                        .table td { padding: 12px; border-bottom: 1px solid #eee; }
                        .total { font-size: 20px; font-weight: bold; text-align: right; margin-top: 30px; }
                        .footer { margin-top: 60px; text-align: center; color: #999; font-size: 12px; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <div class="store-name">${storeSettings.storeName}</div>
                        <div class="invoice-title">Sales Invoice</div>
                    </div>
                    
                    <div class="details">
                        <div class="row">
                            <span class="label">Date:</span>
                            <span>${new Date(sale.date).toLocaleDateString()} ${new Date(sale.date).toLocaleTimeString()}</span>
                        </div>
                        <div class="row">
                            <span class="label">Invoice #:</span>
                            <span>INV-${sale.id}</span>
                        </div>
                    </div>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Item Description</th>
                                <th>Quantity</th>
                                <th>Unit Price</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>${sale.product_name}</td>
                                <td>${sale.quantity}</td>
                                <td>${storeSettings.currency} ${sale.sell_price.toFixed(2)}</td>
                                <td>${storeSettings.currency} ${(sale.sell_price * sale.quantity).toFixed(2)}</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="total">
                        Total Amount: ${storeSettings.currency} ${(sale.sell_price * sale.quantity).toFixed(2)}
                    </div>

                    <div class="footer">
                        Thank you for your business!<br>
                        Generated by My Store Retail Manager
                    </div>
                </body>
            </html>
        `;

        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    }
}
